### ISSUE TITLE
Some genomes result in "Index out of range" Errors in Step 5

### ISSUE THREAD

**Issue by TobyBaril** [niccw/repeatcraftp#2]
When running some genomes under exactly the same parameters, the following errors occur. Input files look the same as far as I can see, so unsure what is causing the errors?

```
Step 5: Merging GFF records by labels...
Removing tmp files...
Traceback (most recent call last):
  File "/home/toby/Programs/repeatCraft/repeatcraft.py", line 161, in <module>
    truemergeltrm.trumergeLTR(rmgff=outputnamelabel, outfile="ltrmerge.tmp.gff")
  File "/home/toby/Programs/repeatCraft/helper/truemergeltrm.py", line 46, in trumergeLTR
    ltrgroup = re.findall(r"LTRgroup=(.*)$", col[8])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/toby/Programs/repeatCraft/repeatcraft.py", line 198, in <module>
    os.remove(outputnamemerge_tobesort)
FileNotFoundError: [Errno 2] No such file or directory: '/home/toby/Documents/riceGenome/matchaTest/ricematchaTEAdLiSiMasker/rice_mergedRepeats/rice.rmerge.gff.tmp'
```

**Comment by TobyBaril** [comment]
Fixed/Avoided by running strict merge

**Comment by niccw** [comment]
Sorry for the late reply.
I tried to improve the way parsing the intermediate file. Since I am not sure which lines/steps cause the error, I added error messages showing the problematic lines. Now users can skip those lines (if it is just stupid parsing error) as a quick fix.
