### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by Giacomoggioli** [niccw/repeatcraftp#3]
Hello, 
I am getting this error while running RepeatCraft with the output obtained from RepeatMasker 4.0.9:
```
Step 1: Reformating GFF...
       Parsing LTR_FINDER GFF...
Step 2: Labelling short TEs...
Missing mapfile, use unite size for all TEs except simple repeat, low complexity and satellite.
'tRNA' is not in the mapfile. Skip filtering tRNAStep 3: Labelling LTR groups...
Updated LTR.gff with LTRgroup attribute to:ltrfinder_reformat.gffStep 4: Labelling TE groups...(loose mode)
Progress:867465/867466...Step 5: Merging GFF records by labels...
Removing tmp files...
Done
Traceback (most recent call last):
  File "/data/SBCS-MartinDuranLab/02-Chema/src/repeatcraftp/repeatcraft.py", line 165, in <module>
    extraTrueMergeTEm.extratruemergete(gffp="ltrmerge.tmp.gff",outfile=outputnamemerge_tobesort )
  File "/data/SBCS-MartinDuranLab/02-Chema/src/repeatcraftp/helper/extraTrueMergeTEm.py", line 69, in extratruemergete
    tchrom, tfamily, tnumber = tegroup.split("|")
ValueError: too many values to unpack (expected 3)
```
Does this depend on the fact that I am using RepeatMasker 4.0.9 instead of 4.0.7 or 4.0.6?
Best,
Giacomo Moggioli

**Comment by niccw** [comment]
@Giacomoggioli   
Can you post the first few lines of the GFF files? (from LTR finder and repeatmasker)?
